#!/bin/bash
#
# vyatta-update-watchdog.sh: watchdog configuration script
#
# Maintainer: Daniil Baturin <daniil at baturin dot org>
#
# Copyright (C) 2013 SO3Group
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

# Config path prefix
WDT_PATH="system watchdog"

API=cli-shell-api

WDT_CONFIG=/etc/watchdog.conf

# There is an option for module loading in /etc/defaults/watchdog
# but it's probably better to find out something went wrong with
# it during commit
function load_module
{
    MODULE=$($API returnValue $WDT_PATH driver)
    lsmod | grep $MODULE > /dev/null
    if [ $? != 0 ]; then
        sudo modprobe $MODULE
        if [ $? != 0 ]; then
            echo "Could not load watchdog driver"
            exit 1
        fi
    fi
}

# Write a config line
function write_cfg
{
    sudo sh -c "echo $1 >> $WDT_CONFIG"
}

# Write a config header
function config_header
{
    sudo sh -c "echo '# WARNING: This file automatically generated by' >> $WDT_CONFIG"
    sudo sh -c "echo '# CLI configuration front-end.' >> $WDT_CONFIG"
    sudo sh -c "echo '# Do not edit it manually, your changes will be' >> $WDT_CONFIG"
    sudo sh -c "echo '# overwritten on next commit or reboot' >> $WDT_CONFIG"
}

# Setup free memory test
#
# Watchdog daemon (lazy butt) counts memory in pages.
# We don't want to make the user learn what a page is
# so we convert megabytes to the current system pages.
function config_freemem
{
    MEMORY_MB=$($API returnValue system watchdog tests free-memory)
    PAGE_SIZE=$(getconf PAGESIZE)
    MEMORY_PAGES=$(($MEMORY_MB*1024*1024/$PAGE_SIZE))
    write_cfg "min-memory = $MEMORY_PAGES"
}

# Setup max load test
function config_max_load
{
    # tests system-load interval-1
    if $API exists $WDT_PATH tests system-load interval-1; then
        LOAD_1=$($API returnValue $WDT_PATH tests system-load interval-1)
        write_cfg "max-load-1 = $LOAD_1"
    fi

    # tests system-load interval-5
    if $API exists $WDT_PATH tests system-load interval-5; then
        LOAD_5=$($API returnValue $WDT_PATH tests system-load interval-5)
        write_cfg "max-load-5 = $LOAD_5"
    fi

    # tests system-load interval-15
    if $API exists $WDT_PATH tests system-load interval-15; then
        LOAD_15=$($API returnValue $WDT_PATH tests system-load interval-15)
        write_cfg "max-load-15 = $LOAD_15"
    fi
}

# Setup ping test
function config_ping
{
    ping_list=$($API returnValues $WDT_PATH tests ping address)
    eval "PING_HOSTS=($ping_list)"

    for i in "${PING_HOSTS[@]}"; do
        write_cfg "ping = $i"
    done
}

# Setup process test
function config_process
{
    # Processes that can render the system
    # unusable or inaccessible in case they fail.
    BGPD_PID="/var/run/quagga/bgpd.pid"
    OSPFD_PID="/var/run/quagga/ospfd.pid"
    OSPF6D_PID="/var/run/quagga/ospf6d.pid"
    RIPD_PID="/var/run/quagga/ripd.pid"
    ZEBRA_PID="/var/run/quagga/zebra.pid"
    SSHD_PID="/var/run/sshd.pid"

    # On systems with no real time clock
    # absense of working NTP _can_ render
    # the system unusable in case it relies
    # on cryptographic algorithms like Kerberos
    # or SSL that require accurate system time
    NTPD_PID="/var/run/ntpd.pid"

    # Predefined processes
    if $API exists $WDT_PATH tests process service bgp; then
        write_cfg "pidfile = $BGPD_PID"
    fi

    if $API exists $WDT_PATH tests process service ospf; then
        write_cfg "pidfile = $OSPFD_PID"
    fi

    if $API exists $WDT_PATH tests process service ospf6; then
        write_cfg "pidfile = $OSPF6_PID"
    fi

    if $API exists $WDT_PATH tests process service rip; then
        write_cfg "pidfile = $RIPD_PID"
    fi

    if $API exists $WDT_PATH tests process service routing-engine; then
        write_cfg "pidfile = $ZEBRA_PID"
    fi

    if $API exists $WDT_PATH tests process service ssh; then
        write_cfg "pidfile = $SSHD_PID"
    fi

    if $API exists $WDT_PATH tests process service ntp; then
        write_cfg "pidfile = $NTPD_PID"
    fi

    # User defined processes
    pid_list=$($API returnValues $WDT_PATH tests process user-defined pid-file)
    eval "PID_FILES=($pid_list)"

    for i in "${PID_FILES[@]}"; do
        write_cfg "pidfile = $i"
    done
}

# Setup user defined test
function config_user_defined
{
    TEST_EXECUTABLE=$($API returnValue $WDT_PATH tests user-defined executable)
    TEST_TIMEOUT=$($API returnValue $WDT_PATH tests user-defined timeout)

    if [ -z $TEST_EXECUTABLE ]; then
        echo "Test executable must be defined"
        exit 1
    fi

    write_cfg "test-binary = $TEST_EXECUTABLE"
    write_cfg "test-timeout = $TEST_TIMEOUT"
}

# Setup repair program
function config_repair
{
    REPAIR_EXECUTABLE=$($API returnValue $WDT_PATH repair executable)
    REPAIR_TIMEOUT=$($API returnValue $WDT_PATH repair timeout)

    if [ -z $REPAIR_EXECUTABLE ]; then
        echo "Repair executable must be defined"
        exit 1
    fi

    write_cfg "repair-binary = $REPAIR_EXECUTABLE"
    write_cfg "repair-timeout = $REPAIR_TIMEOUT"
}

# Setup daemon options
function config_options
{
    if $API exists $WDT_PATH options realtime; then
        write_cfg "realtime = yes"
    fi

    RESET_INTERVAL=$($API returnValue $WDT_PATH options reset-interval)
    write_cfg "interval = $RESET_INTERVAL"
}

########### Main ###########

# system watchdog driver
if $API exists $WDT_PATH driver; then
    load_module
fi

# Wipe the old config
sudo sh -c "echo '' > $WDT_CONFIG"

# Write header with "do not edit" warning
config_header

## system watchdog tests
if $API exists $WDT_PATH tests; then
    # system watchdog tests free-memory
    if $API exists $WDT_PATH tests free-memory; then
        config_freemem
    fi

    # system watchdog tests system-load
    if $API exists $WDT_PATH tests system-load; then
        config_max_load
    fi

    # system watchdog tests ping
    #
    # There is a bug in watchdog daemon that
    # makes ping test unusable on some configurations.
    # Disabled until fix is available.
    #
    #if $API exists $WDT_PATH tests ping; then
    #    config_ping
    #fi

    # system watchdog tests process
    if $API exists $WDT_PATH tests process; then
        config_process
    fi

    # system watchdog tests user-defined
    if $API exists $WDT_PATH tests user-defined; then
        config_user_defined
    fi
fi

# system watchdog repair
if $API exists $WDT_PATH repair; then
    config_repair
fi

# system watchdog options
if $API exists $WDT_PATH options; then
    config_options
fi
